# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b07e3647c1ed0327a7e58c08aa6418bf466ef2e6006b84e921affe544e00e0889d9ae69e9633e1bc2bfbeaf1061afadd63aa22be4ab4f24b40827479719913

test:
  secret_key_base: 4287e75d0f47813344ef9bdff4b01e0aacd1efab92994bc925da22ddbdad23a127cd246dbeec44f28ec45bae95f99adbe022c316b3fabe5ca88f226707ee138f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
